apiVersion: v1
kind: Secret
metadata:
  name: feedpulse-secrets
  namespace: feedpulse
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_JWT_SECRET"
  ADMIN_EMAIL: "admin@feedpulse.local"
  ADMIN_PASSWORD: "CHANGE_ME_ADMIN_PASSWORD"
  GEMINI_API_KEY: "CHANGE_ME_GEMINI_API_KEY"
  MONGO_URI: "mongodb://mongo.feedpulse.svc.cluster.local:27017"

