apiVersion: v1
kind: ConfigMap
metadata:
  name: feedpulse-config
  namespace: feedpulse
data:
  MONGO_DATABASE: "feedpulse"
  AUTH_SERVICE_URL: "http://auth-service.feedpulse.svc.cluster.local:8081"
  FEEDBACK_SERVICE_URL: "http://feedback-service.feedpulse.svc.cluster.local:8082"
  AI_SERVICE_URL: "http://ai-service.feedpulse.svc.cluster.local:8083"

